# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['17'] #Support LTS releases 17 and the latest release supported by Micronaut.
        runtime: ['netty']
        include: # Test more server runtimes on Java 17 only (to reduce number of combinations)
          - java: '17'
            runtime: 'jetty'
          - java: '17'
            runtime: 'tomcat'
          - java: '17'
            runtime: 'undertow'

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Set up JDKs with Matrix Build
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Build with Gradle Wrapper
        run: ./gradlew build --warning-mode=all -Pmicronaut.runtime=${{ matrix.runtime }} # value 'fail' would be better but the build even this breaks: "mn create-app mytest && cd mytest && ./gradlew clean build --warning-mode fail"
