# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Continuous Integration

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['11', '16'] #Support LTS releases 8 and 11 and the latest release supported by Micronaut.
        runtime: ['netty']
        gradle_args: ['-Dorg.gradle.jvmargs=--illegal-access=permit']
        include: # Test more server runtimes on Java 8 only (to reduce number of combinations)
          - java: '8'
            runtime: 'netty'
            gradle_args: ''
          - java: '8'
            runtime: 'jetty'
            gradle_args: ''
          - java: '8'
            runtime: 'tomcat'
            gradle_args: ''
          - java: '8'
            runtime: 'undertow'
            gradle_args: ''

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Set up JDKs with Matrix Build
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Build with Gradle Wrapper
        run: ./gradlew build --warning-mode=fail -Pmicronaut.runtime=${{ matrix.runtime }} ${{ matrix.gradle_args }}
